# Base URL of the site, the only required config argument
base_url = "https://pawndev-hermit-zola.netlify.app/"

# Used in RSS by default
title = "Hermit Zola"
description = "My blog"
# The default language, used in RSS
default_language = "en"

# Theme name to use
# theme = ""

# Whether to generate a RSS feed automatically
generate_feed = false

# The number of articles to include in the RSS feed. Will include all items if
# not set (the default).
# rss_limit = 20

# The taxonomies to be rendered for that site and their configuration
# Example:
#     taxonomies = [
#       {name = "tags", rss = true}, # each tag will have its own RSS feed
#       {name = "categories", paginate_by = 5},  # 5 items per page for a term
#       {name = "authors"}, # Basic definition: no RSS or pagination
#     ]
#
taxonomies = [
           {name = "tags", rss = true}
]

# The additional languages for that site
# Example:
#     languages = [
#       {code = "fr", rss = true}, # there will be a RSS feed for French content
#       {code = "it"}, # there won't be a RSS feed for Italian content
#     ]
#
languages = []

# Whether to compile the Sass files found in the `sass` directory
compile_sass = true

# Whether to build a search index out of the pages and section
# content for the `default_language`
build_search_index = false

# A list of glob patterns specifying asset files to ignore when
# processing the content directory.
# Defaults to none, which means all asset files are copied over to the public folder.
# Example:
#     ignored_content = ["*.{graphml,xlsx}", "temp.*"]
ignored_content = []

# A list of directories to search for additional `.sublime-syntax` files in.
extra_syntaxes = []

[markdown]
# Highlight all code blocks found
highlight_code = true

# Which theme to use for the code highlighting.
# See below for list of accepted values
highlight_theme = "visual-studio-dark"
# When set to "true", emoji aliases translated to their corresponding
# Unicode emoji equivalent in the rendered Markdown files. (e.g.: :smile: => 😄)
render_emoji = true

# Whether external links are to be opened in a new tab
# If this is true, a `rel="noopener"` will always automatically be added for security reasons
external_links_target_blank = false

# Whether to set rel="nofollow" for all external links
external_links_no_follow = false

# Whether to set rel="noreferrer" for all external links
external_links_no_referrer = false

# Whether smart punctuation is enabled (changing quotes, dashes, dots in their typographic form)
# For example, `...` into `…`, `"quote"` into `“curly”` etc
smart_punctuation = false

# Optional translation object. The key if present should be a language code
[translations]
[translations.fr]
tags = "Catégories"
[translations.en]
tags = "Tags"

# You can put any kind of data in there and it
# will be accessible in all templates
[extra]
#home_subtitle = "Some profound and catchy statement"
home_subtitle = "If brute force doesn’t solve your problems, then you aren’t using enough. "

footer_copyright = ' &#183; <a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'

hermit_menu = [
    { link = "posts", name = "Posts" },
    { link = "tags",  name = "Tags" },
    { link = "about", name = "About" }
]

hermit_social = [
    { name = "twitter", link = "https://twitter.com" },
    { name = "github", link = "https://github.com" },
    { name = "email", link = "mailto:author@domain.com" }
]

accent_color = "grey"

[extra.highlightjs]
enable = false
clipboard = false
theme = "vs2015"
notebook = false

[extra.author]
name = "The Author"
email = "author@domain.com"

[extra.google_analytics]
enable = false
id = "UA-4XXXXXXX-X"
